#!/usr/bin/sh
#
# Copyright (c) 2023 by MULTIPLE AUTHORS
# Part of the CS study course project.
#

set -e
set -u

./mvnw clean package install

./mvnw -pl "client" clean assembly:assembly
./mvnw -pl "host" clean assembly:assembly
