name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version in format X.X.X'
        required: true
        default: '1.0.0'
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "adopt"
          check-latest: false

      - name: Change wrapper permissions
        run: chmod +x ./mvnw

      - name: Clean build dir
        run: ./mvnw clean

      - name: Install library
        run: ./mvnw package install -pl lib

      - name: Package to JAR
        run: ./mvnw package -pl client,host

      - name: Create tag v${{ github.event.inputs.version }}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ github.event.inputs.version }}
          tag_exists_error: true
          message: "Release ${{ github.event.inputs.version }}"
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/.bin/*.jar
            ${{ github.workspace }}/.start/
          tag_name: v${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
